/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 09-16-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class Sample {
   // The no argument constructor 
   public Sample() {
      // more code here
      // 3rd commit
      this(DEFAULT_SIZE);
   }

   // 3rd commit
   // Constructor with one argument 
   public TestObject2(Integer ObjectSize) {
     size = ObjectSize;  
   }
}