/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 09-16-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class Sample {

// second commit
private static final Integer DEFAULT_SIZE = 10;
Integer size;

   // The no argument constructor 
   public Sample() {
      // more code here
   }
}